// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAva3lpdh1RARU3AYuFvFt2h6DhPWjfmpo',
    appId: '1:680202233178:web:b169860f42dc42b5d5bf63',
    messagingSenderId: '680202233178',
    projectId: 'ri-rs-28750',
    authDomain: 'ri-rs-28750.firebaseapp.com',
    storageBucket: 'ri-rs-28750.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY4ffbqL5OJO2nPXQrXkP9EmD3iD6lucI',
    appId: '1:680202233178:android:795dce9ffde2d16dd5bf63',
    messagingSenderId: '680202233178',
    projectId: 'ri-rs-28750',
    storageBucket: 'ri-rs-28750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmYjTYK4YdNPEaalE-8zUUwWw60gSszw8',
    appId: '1:680202233178:ios:db0b3ad0d7206f7cd5bf63',
    messagingSenderId: '680202233178',
    projectId: 'ri-rs-28750',
    storageBucket: 'ri-rs-28750.firebasestorage.app',
    iosBundleId: 'com.example.mobilers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmYjTYK4YdNPEaalE-8zUUwWw60gSszw8',
    appId: '1:680202233178:ios:db0b3ad0d7206f7cd5bf63',
    messagingSenderId: '680202233178',
    projectId: 'ri-rs-28750',
    storageBucket: 'ri-rs-28750.firebasestorage.app',
    iosBundleId: 'com.example.mobilers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAva3lpdh1RARU3AYuFvFt2h6DhPWjfmpo',
    appId: '1:680202233178:web:2837b0c0d345a3cfd5bf63',
    messagingSenderId: '680202233178',
    projectId: 'ri-rs-28750',
    authDomain: 'ri-rs-28750.firebaseapp.com',
    storageBucket: 'ri-rs-28750.firebasestorage.app',
  );
}
